# Generated by Django 2.2.7 on 2019-11-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20191121_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created'], 'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
    ]
