# Generated by Django 2.2.7 on 2019-12-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20191203_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bariloche',
            options={'ordering': ['-created'], 'verbose_name': 'foto', 'verbose_name_plural': 'Bariloche'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created'], 'verbose_name': 'foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterField(
            model_name='bariloche',
            name='image',
            field=models.ImageField(upload_to='Bariloche', verbose_name='Imagen'),
        ),
    ]
