# Generated by Django 2.2.7 on 2019-12-04 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20191203_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bariloche',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created'], 'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
        migrations.AddField(
            model_name='photo',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
