# Generated by Django 2.2.6 on 2019-12-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20191203_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='link',
        ),
    ]
