# Generated by Django 2.2.7 on 2019-12-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_remove_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Referencia de imagen'),
        ),
    ]
