# Generated by Django 3.0 on 2019-12-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20191204_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created'], 'verbose_name': 'foto', 'verbose_name_plural': 'Bariloche'},
        ),
    ]
