# Generated by Django 3.0 on 2019-12-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20191206_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ba',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='bariloche', verbose_name='Imagen'),
        ),
    ]
